image: docker:latest
services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay
  CI_VERSION: '6.6.$CI_PIPELINE_IID'

stages:
- build
- package
- trigger

build-backend:
  image: openjdk:10.0.2-jdk-slim
  stage: build
  before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  cache:
    paths:
    - .gradle/wrapper
    - .gradle/caches
  script:
  - ./gradlew assemble
  artifacts:
    expire_in: 1 week
    paths:
    - jb-web/build/libs/JuniperBot.jar

build-docker:
  stage: package
  script:
  - docker build -t registry.gitlab.com/juniperbot/backend:$CI_COMMIT_REF_NAME -t registry.gitlab.com/juniperbot/backend:$CI_VERSION .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/juniperbot/backend:$CI_COMMIT_REF_NAME
  - docker push registry.gitlab.com/juniperbot/backend:$CI_VERSION
  dependencies:
  - build-backend
  only:
  - master
  - develop

trigger-deploy:
  stage: trigger
  script:
  - apk add --update curl && rm -rf /var/cache/apk/*
  - curl --request POST --form "token=$CI_JOB_TOKEN" --form "ref=$CI_COMMIT_REF_NAME" https://gitlab.com/api/v4/projects/$INFRASTRUCTURE_PROJECT_ID/trigger/pipeline
  only:
  - master
  - develop
