spring:
  cloud:
    consul:
      enabled: false
      discovery:
        healthCheckPath: /api/public/health
        healthCheckInterval: 15s
  application:
    version: "@build.version@"
    timestamp: "@build.timestamp@"
    name: "JuniperBot-Worker"
  jpa:
    generate-ddl: "false"
    open-in-view: "false"
    hibernate:
      ddl-auto: "none"
    properties:
      hibernate:
        dialect: "ru.juniperbot.common.persistence.support.ExPostgreSQLDialect"
        jdbc:
          lob:
            non_contextual_creation: "true"
  liquibase:
    change-log: "classpath:db/master.xml"
  quartz:
    overwriteExistingJobs: "true"
    properties:
      org.quartz.scheduler.instanceName: "juniperbot-spring-boot-quartz"
      org.quartz.scheduler.instanceId: "AUTO"
      org.quartz.threadPool.threadCount: "15"
      org.quartz.jobStore.class: "org.quartz.impl.jdbcjobstore.JobStoreTX"
      org.quartz.jobStore.driverDelegateClass: "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
      org.quartz.jobStore.useProperties: "true"
      org.quartz.jobStore.misfireThreshold: "60000"
      org.quartz.jobStore.tablePrefix: "qrtz_"
      org.quartz.jobStore.isClustered: "false"
      org.quartz.jobStore.clusterCheckinInterval: "20000"

dependencies:
  jda.version: "@JDA.version@"
  lavaPlayer.version: "@lavaplayer.version@"
  spring.version: "@spring.version@"
